apiVersion: 1
datasources:
  - uid: local-prometheus
    type: prometheus
    name: Prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 10s
